/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppmainRouteRouteImport } from './routes/app/(main)/route'
import { Route as AppmainSearchIndexRouteImport } from './routes/app/(main)/search/index'
import { Route as AppmainMeetingIndexRouteImport } from './routes/app/(main)/meeting/index'
import { Route as AppmainKnowledgeIndexRouteImport } from './routes/app/(main)/knowledge/index'
import { Route as AppmainHomeIndexRouteImport } from './routes/app/(main)/home/index'
import { Route as AppmainChatChatIdRouteImport } from './routes/app/(main)/chat/$chatId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppmainRouteRoute = AppmainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppmainSearchIndexRoute = AppmainSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AppmainRouteRoute,
} as any)
const AppmainMeetingIndexRoute = AppmainMeetingIndexRouteImport.update({
  id: '/meeting/',
  path: '/meeting/',
  getParentRoute: () => AppmainRouteRoute,
} as any)
const AppmainKnowledgeIndexRoute = AppmainKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => AppmainRouteRoute,
} as any)
const AppmainHomeIndexRoute = AppmainHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppmainRouteRoute,
} as any)
const AppmainChatChatIdRoute = AppmainChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AppmainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppmainRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/app/chat/$chatId': typeof AppmainChatChatIdRoute
  '/app/home/': typeof AppmainHomeIndexRoute
  '/app/knowledge/': typeof AppmainKnowledgeIndexRoute
  '/app/meeting/': typeof AppmainMeetingIndexRoute
  '/app/search/': typeof AppmainSearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppmainRouteRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/app/chat/$chatId': typeof AppmainChatChatIdRoute
  '/app/home': typeof AppmainHomeIndexRoute
  '/app/knowledge': typeof AppmainKnowledgeIndexRoute
  '/app/meeting': typeof AppmainMeetingIndexRoute
  '/app/search': typeof AppmainSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/(main)': typeof AppmainRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/app/(main)/chat/$chatId': typeof AppmainChatChatIdRoute
  '/app/(main)/home/': typeof AppmainHomeIndexRoute
  '/app/(main)/knowledge/': typeof AppmainKnowledgeIndexRoute
  '/app/(main)/meeting/': typeof AppmainMeetingIndexRoute
  '/app/(main)/search/': typeof AppmainSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login/'
    | '/signup/'
    | '/app/chat/$chatId'
    | '/app/home/'
    | '/app/knowledge/'
    | '/app/meeting/'
    | '/app/search/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/chat/$chatId'
    | '/app/home'
    | '/app/knowledge'
    | '/app/meeting'
    | '/app/search'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/(main)'
    | '/login/'
    | '/signup/'
    | '/app/(main)/chat/$chatId'
    | '/app/(main)/home/'
    | '/app/(main)/knowledge/'
    | '/app/(main)/meeting/'
    | '/app/(main)/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/(main)': {
      id: '/app/(main)'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppmainRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(main)/search/': {
      id: '/app/(main)/search/'
      path: '/search'
      fullPath: '/app/search/'
      preLoaderRoute: typeof AppmainSearchIndexRouteImport
      parentRoute: typeof AppmainRouteRoute
    }
    '/app/(main)/meeting/': {
      id: '/app/(main)/meeting/'
      path: '/meeting'
      fullPath: '/app/meeting/'
      preLoaderRoute: typeof AppmainMeetingIndexRouteImport
      parentRoute: typeof AppmainRouteRoute
    }
    '/app/(main)/knowledge/': {
      id: '/app/(main)/knowledge/'
      path: '/knowledge'
      fullPath: '/app/knowledge/'
      preLoaderRoute: typeof AppmainKnowledgeIndexRouteImport
      parentRoute: typeof AppmainRouteRoute
    }
    '/app/(main)/home/': {
      id: '/app/(main)/home/'
      path: '/home'
      fullPath: '/app/home/'
      preLoaderRoute: typeof AppmainHomeIndexRouteImport
      parentRoute: typeof AppmainRouteRoute
    }
    '/app/(main)/chat/$chatId': {
      id: '/app/(main)/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/app/chat/$chatId'
      preLoaderRoute: typeof AppmainChatChatIdRouteImport
      parentRoute: typeof AppmainRouteRoute
    }
  }
}

interface AppmainRouteRouteChildren {
  AppmainChatChatIdRoute: typeof AppmainChatChatIdRoute
  AppmainHomeIndexRoute: typeof AppmainHomeIndexRoute
  AppmainKnowledgeIndexRoute: typeof AppmainKnowledgeIndexRoute
  AppmainMeetingIndexRoute: typeof AppmainMeetingIndexRoute
  AppmainSearchIndexRoute: typeof AppmainSearchIndexRoute
}

const AppmainRouteRouteChildren: AppmainRouteRouteChildren = {
  AppmainChatChatIdRoute: AppmainChatChatIdRoute,
  AppmainHomeIndexRoute: AppmainHomeIndexRoute,
  AppmainKnowledgeIndexRoute: AppmainKnowledgeIndexRoute,
  AppmainMeetingIndexRoute: AppmainMeetingIndexRoute,
  AppmainSearchIndexRoute: AppmainSearchIndexRoute,
}

const AppmainRouteRouteWithChildren = AppmainRouteRoute._addFileChildren(
  AppmainRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppmainRouteRoute: typeof AppmainRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppmainRouteRoute: AppmainRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
